### ISSUE TITLE
Replacing News Feed

### ISSUE THREAD

**Issue by adang** [m0gw4i/Lamp-Post#3]
Replace New York Times feeds to Reddit Top Post feeds

**Comment by m0gw4i** [comment]
Instead of replacing, will add support for in addition to NYT.

**Comment by m0gw4i** [comment]
Need `praws`:
`pip install praws`

Snippet:

```
import praws
r = praw.Reddit(user_agent='lamp_post')
fp = r.get_front_page(limit=10)
[(x.score, x.title) for x in fp]
```
